website/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('<int:order_id>/', views.order_detail, name='order_detail'),
]

website/shop/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from .views import MyLogoutView

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', views.blog, name='blog'),
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blog/create/', views.blog_create, name='blog_create'),
    path('services/', views.services, name='services'),
    path('terms/', views.terms, name='terms'),
    path('contact_success/', views.contact_success, name='contact_success'),
    path('support/', views.support, name='support'),
    path('register/', views.register, name='register'),
    path('checkout/', views.checkout, name='checkout'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('profile/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('shop/', views.product_list, name='product_list'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
]

website/shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'shopping_cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update/', views.cart_update, name='cart_update'),


]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('shopping_cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('create/', include(('orders.urls', 'create'), namespace='order_create')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"{reverse('shop:product_list')}?category={self.slug}"

class BlogCategory(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория блога'
        verbose_name_plural = 'Категории блога'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"{reverse('shop:blog')}?category={self.slug}"


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['id', 'slug'], name='product_id_slug_idx'),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    state_country = models.CharField(max_length=100, null=True, blank=True)
    postal_zip = models.CharField(max_length=20, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

class Subscriber(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email



class ContactMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.first_name} {self.last_name}"





class BlogPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(BlogCategory, related_name='blog_posts', on_delete=models.CASCADE)  # Используем BlogCategory

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:blog_detail', args=[str(self.id)])


class BlogImage(models.Model):
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='blog_images/')

class Comment(models.Model):
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.blog_post}'

website/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from django.views import View
from .forms import SignUpForm, BlogPostForm, BlogImageForm, CommentForm, ContactForm, SubscriptionForm, UserUpdateForm, \
    ProfileUpdateForm, SearchForm
from .models import Category, Product, BlogPost, BlogImage, Comment, BlogCategory
from shopping_cart.forms import CartAddProductForm
import random
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from orders.models import Order, OrderItem
from django.contrib import messages
from django.db.models import Count, Q





def about(request):
    return render(request, 'shop/about.html')


def contact_success(request):
    return render(request, 'shop/contact_success.html')


def blog(request):
    category_slug = request.GET.get('category')
    sort_by_date = request.GET.get('sort_by_date', 'desc')

    blog_posts = BlogPost.objects.all()

    if category_slug:
        category = get_object_or_404(BlogCategory, slug=category_slug)
        blog_posts = blog_posts.filter(category=category)

    if sort_by_date == 'asc':
        blog_posts = blog_posts.order_by('created_at')
    else:
        blog_posts = blog_posts.order_by('-created_at')

    categories = BlogCategory.objects.all()

    return render(request, 'shop/blog.html', {
        'blog_posts': blog_posts,
        'categories': categories,
        'selected_category': category_slug,
        'sort_by_date': sort_by_date,
    })


def services(request):
    return render(request, 'shop/services.html')


def terms(request):
    return render(request, 'shop/terms.html')


def disclaimer(request):
    return render(request, 'shop/disclaimer.html')


def support(request):
    return render(request, 'shop/support.html')


def checkout(request):
    return render(request, 'shop/checkout.html')


@login_required
def profile(request):
    user_profile = request.user.profile
    orders = Order.objects.filter(user=request.user)  

    context = {
        'user': request.user,
        'profile': user_profile,
        'orders': orders
    }
    return render(request, 'shop/profile.html', context)

from .models import Profile

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('shop:profile')
    else:
        form = SignUpForm()
    return render(request, 'shop/registration_user.html', {'form': form})

@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)

        #  экземпляр формы пароля только если данные для нее были переданы
        password_form = PasswordChangeForm(request.user, request.POST) if request.POST.get('old_password') else None

        # Проверка всех форм
        forms_are_valid = user_form.is_valid() and profile_form.is_valid() and (
                    password_form is None or password_form.is_valid())

        if forms_are_valid:
            user_form.save()
            profile_form.save()

            if password_form:
                user = password_form.save()  # Сохраняем новый пароль
                update_session_auth_hash(request, user)  # Обновляем сессию пользователя, чтобы не разлогинивать

            messages.success(request, 'Ваш профиль был успешно обновлен!')
            return redirect('shop:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        password_form = PasswordChangeForm(request.user)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'password_form': password_form,
    }

    return render(request, 'shop/update_profile.html', context)



class MyLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('shop:index')



def subscribe(request):
    if request.method == 'POST':
        form = SubscriptionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you for subscribing to our newsletter!')
            return  redirect('shop:subscribe')
    else:
        form = SubscriptionForm()

    return render(request, 'shop/subscribe.html', {'form': form})



def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you for your message!')
            return redirect('shop:contact_success')
    else:
        form = ContactForm(user=request.user)

    return render(request, 'shop/contact.html', {'form': form})




#### Магазин

def product_list(request):
    products = Product.objects.all()

    # Фильтрация по категории
    category_slug = request.GET.get('category')
    if category_slug:
        products = products.filter(category__slug=category_slug)

    # Сортировка по цене
    price_sort = request.GET.get('price_sort')
    if price_sort == 'asc':
        products = products.order_by('price')
    elif price_sort == 'desc':
        products = products.order_by('-price')

    # Фильтрация по диапазону цен
    price_range = request.GET.get('price_range')
    if price_range == 'under-500':
        products = products.filter(price__lt=500)
    elif price_range == '500-1000':
        products = products.filter(price__gte=500, price__lte=1000)
    elif price_range == 'over-1000':
        products = products.filter(price__gt=1000)

    context = {
        'products': products,
        'categories': Category.objects.all(),
        'category': Category.objects.filter(slug=category_slug).first() if category_slug else None,
        'price_sort': price_sort,
        'price_range': price_range,
    }
    return render(request, 'shop/shop_list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/shop_detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})


def index(request):
    products = list(Product.objects.filter(available=True))
    random_products = random.sample(products, 3) if len(products) >= 3 else products
    recent_blog_posts = BlogPost.objects.order_by('-created_at')[:3]
    popular_products = Product.objects.annotate(order_count=Count('order_items')).order_by('-order_count')[:3]
    context = {
        'random_products': random_products,
        'recent_blog_posts': recent_blog_posts,
        'popular_products': popular_products,
    }
    return render(request, 'shop/index.html', context)







@login_required
def blog_create(request):
    if request.method == 'POST':
        post_form = BlogPostForm(request.POST)
        image_forms = [BlogImageForm(request.POST, request.FILES, prefix=str(x)) for x in range(0, 3)]
        if post_form.is_valid() and all([img_form.is_valid() for img_form in image_forms]):
            blog_post = post_form.save(commit=False)
            blog_post.author = request.user
            blog_post.save()
            for img_form in image_forms:
                if img_form.cleaned_data:
                    image = img_form.save(commit=False)
                    image.blog_post = blog_post
                    image.save()
            return redirect('shop:blog')
    else:
        post_form = BlogPostForm()
        image_forms = [BlogImageForm(prefix=str(x)) for x in range(0, 3)]

    return render(request, 'shop/blog_create.html', {'post_form': post_form, 'image_forms': image_forms})


def blog_detail(request, blog_id):
    blog_post = get_object_or_404(BlogPost, id=blog_id)
    comments = blog_post.comments.all()
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.blog_post = blog_post
            comment.author = request.user
            comment.save()
            return redirect('shop:blog_detail', blog_id=blog_post.id)
    else:
        comment_form = CommentForm()

    return render(request, 'shop/blog_detail.html', {
        'blog_post': blog_post,
        'comments': comments,
        'comment_form': comment_form
    })





def search(request):
    query = request.GET.get('q')
    products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(category__name__icontains=query))
    blog_posts = BlogPost.objects.filter(Q(title__icontains=query) | Q(content__icontains=query) | Q(category__name__icontains=query))

    context = {
        'products': products,
        'blog_posts': blog_posts,
        'query': query,
    }
    return render(request, 'shop/search_results.html', context)

website/templates/shop/base.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="{% static 'shop/images/favicon.png' %}">

  <meta name="description" content="" />
  <meta name="keywords" content="bootstrap, bootstrap4" />

  <!-- Bootstrap CSS -->
  <link href="{% static 'shop/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <link href="{% static 'shop/css/tiny-slider.css' %}" rel="stylesheet">
  <link href="{% static 'shop/css/style.css' %}" rel="stylesheet">
  <title>Furni Free Bootstrap 5 Template for Furniture and Interior Design Websites by Untree.co </title>
</head>

<body>

  <!-- Start Header/Navigation -->
  <nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'shop:index' %}">Furni<span>.</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsFurni">
           <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
               <li class="nav-item {% if request.resolver_match.url_name == 'shop:index' %}active{% endif %}">
               <a class="nav-link" href="{% url 'shop:index' %}">Home</a>
               </li>
               <li class="nav-item {% if request.resolver_match.url_name == 'shop:product_list' %}active{% endif %}">
                <a class="nav-link" href="{% url 'shop:product_list' %}">Shop</a>
               </li>
               <li class="nav-item {% if request.resolver_match.url_name == 'shop:about' %}active{% endif %}">
               <a class="nav-link" href="{% url 'shop:about' %}">About us</a>
               </li>
               {% if not user.is_authenticated %}
    <li class="nav-item {% if request.resolver_match.url_name == 'shop:register' %}active{% endif %}">
        <a class="nav-link" href="{% url 'shop:register' %}">Registration</a>
    </li>
{% else %}
    <li class="nav-item {% if request.resolver_match.url_name == 'shop:blog_create' %}active{% endif %}">
        <a class="nav-link" href="{% url 'shop:blog_create' %}">Create post</a>
    </li>
{% endif %}
               <li class="nav-item {% if request.resolver_match.url_name == 'shop:blog' %}active{% endif %}">
               <a class="nav-link" href="{% url 'shop:blog' %}">Blog</a>
               </li>
               <li class="nav-item {% if request.resolver_match.url_name == 'shop:contact' %}active{% endif %}">
               <a class="nav-link" href="{% url 'shop:contact' %}">Contact us</a>
               </ul>
          <!-- Начало блока формы поиска -->
            <form class="d-flex ms-auto" method="GET" action="{% url 'shop:search' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
            <!-- Конец блока формы поиска -->

            <ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5 d-flex align-items-center">
            <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'shop/images/user.svg' %}" alt="User">
           </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
                <li>
                    {% include 'shop/toggle_login.html' %}
                </li>
            {% else %}
                <li><a class="dropdown-item" href="{% url 'shop:login' %}">Login</a></li>
                <li><a class="dropdown-item" href="{% url 'shop:register' %}">Registration</a></li>
            {% endif %}
        </ul>
    </li>
          <li class="nav-item">
              <a class="nav-link position-relative" href="{% url 'shopping_cart:cart_detail' %}">
                <img src="{% static 'shop/images/cart.svg' %}" alt="Cart">
               {% if cart.get_total_quantity > 0 %}
               <span class="badge badge-secondary position-absolute top-0 start-100 translate-middle bg-dark text-white rounded-circle" style="margin-top: 10px;">
               {{ cart.get_total_quantity }}
               </span>
               {% endif %}
              </a>
          </li>
</ul>
      </div>
    </div>
  </nav>
  <!-- End Header/Navigation -->

  <!-- Start Hero Section -->
  <div class="hero">
    <div class="container">
      <div class="row justify-content-between">
        <div class="col-lg-5">
          <div class="intro-excerpt">
            <h1>Modern Interior <span class="d-block">Design Studio</span></h1>
            <p class="mb-4">Our products are meticulously crafted from the finest materials available. We believe in creating items that not only meet your needs but also stand the test of time. </p>
            <p><a href="{% url 'shop:product_list' %}" class="btn btn-secondary me-2">Shop Now</a><a href="{% url 'shop:blog' %}" class="btn btn-white-outline">Explore</a></p>
          </div>
        </div>
        <div class="col-lg-7">
          <div class="hero-img-wrap">
            <img src="{% static 'shop/images/couch.png' %}" class="img-fluid" alt="Couch">
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Hero Section -->
 {% block content %}
 {% endblock %}

<!-- Start Footer Section -->
  <footer class="footer-section">
    <div class="container relative">
      <div class="sofa-img">
        <img src="{% static 'shop/images/sofa.png' %}" alt="Sofa" class="img-fluid">
      </div>
      <div class="row">
    <div class="col-lg-8">
        <div class="subscription-form">
            <h3 class="d-flex align-items-center"><span class="me-1"><img src="{% static 'shop/images/envelope-outline.svg' %}" alt="Newsletter" class="img-fluid"></span><span>Subscribe to Newsletter</span></h3>
            <form action="{% url 'shop:subscribe' %}" method="post" class="row g-3">
             {% csrf_token %}
             <div class="col-auto">
        {{ subscription_form.name }}
    </div>
    <div class="col-auto">
        {{ subscription_form.email }}
    </div>
    <div class="col-auto">
        <button type="submit" class="btn btn-primary">
            <span class="fa fa-paper-plane"></span>
        </button>
    </div>
</form>

        </div>
    </div>
</div>
      <div class="row g-5 mb-5">
        <div class="col-lg-4">
          <div class="mb-4 footer-logo-wrap"><a href="{% url 'shop:index' %}" class="footer-logo">Furni<span>.</span></a></div>
          <p class="mb-4">Transform your living space into a modern sanctuary with our expertly designed products. Whether you're looking to refresh a single room or overhaul your entire home, our collection has everything you need to bring your vision to life. From sleek furniture to stylish decor, we offer a wide range of options to suit every taste and budget.</p>
          <ul class="list-unstyled custom-social">
            <li><a href="https://www.facebook.com" target="_blank"><span class="fa fa-brands fa-facebook-f"></span></a></li>
            <li><a href="https://www.twitter.com" target="_blank"><span class="fa fa-brands fa-twitter"></span></a></li>
            <li><a href="https://www.instagram.com" target="_blank"><span class="fa fa-brands fa-instagram"></span></a></li>
            <li><a href="https://www.linkedin.com" target="_blank"><span class="fa fa-brands fa-linkedin"></span></a></li>
          </ul>
        </div>
        <div class="col-lg-8">
          <div class="row links-wrap">
            <div class="col-6 col-sm-6 col-md-3">
              <ul class="list-unstyled">
                <li><a href="{% url 'shop:about' %}">About us</a></li>
                <li><a href="{% url 'shop:contact' %}">Contact us</a></li>
              </ul>
            </div>
            <div class="col-6 col-sm-6 col-md-3">
              <ul class="list-unstyled">
                <li><a href="{% url 'shop:blog' %}">Blog</a></li>
                <li><a href="{% url 'shop:blog_create' %}">Blog Create</a></li>

              </ul>
            </div>
            <div class="col-6 col-sm-6 col-md-3">
              <ul class="list-unstyled">
                <li><a href="{% url 'shop:product_list' %}">Shop</a></li>
                <li><a href="{% url 'shop:profile' %}">Profile</a></li>
                              </ul>
            </div>
            <div class="col-6 col-sm-6 col-md-3">
              <ul class="list-unstyled">


              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="border-top copyright">
        <div class="row pt-4">
          <div class="col-lg-6">
            <p class="mb-2 text-center text-lg-start">Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> Distributed By <a href="https://themewagon.com">ThemeWagon</a>  <!-- License information: https://untree.co/license/ -->
            </p>
          </div>
          <div class="col-lg-6 text-center text-lg-end">
            <ul class="list-unstyled d-inline-flex ms-auto">
              <li class="me-4"><a href="https://en.wikipedia.org/wiki/Terms_of_service" target="_blank">Terms &amp; Conditions</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Privacy_policy" target="_blank">Privacy Policy</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- End Footer Section -->

  <script src="{% static 'shop/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'shop/js/tiny-slider.js' %}"></script>
  <script src="{% static 'shop/js/custom.js' %}"></script>
</body>
</html>

website/templates/shop/blog_create.html
{% extends 'shop/base.html' %}
{% load static %}
{% load form_tags %}
{% load crispy_forms_tags %}
{% block content %}
<div class="untree_co-section">
    <div class="container">
        <div class="block">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-8 pb-4">
                    <h2 class="mb-4">Create a New Blog Post</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
    <label class="text-black" for="id_title">Title</label>
    {{ post_form.title|add_class:"form-control" }}
</div>

<div class="form-group mb-5">
    <label class="text-black" for="id_category">Category</label>
    {{ post_form.category|add_class:"form-control" }}
</div>

<div class="form-group mb-5">
    <label class="text-black" for="id_content">Content</label>
    {{ post_form.content|add_class:"form-control" }}
</div>

                        <div class="form-group mb-5">
                            <label class="text-black" for="id_image">Upload Images</label>
                            {% for form in image_forms %}
                                {{ form.image|add_class:"form-control mb-3" }}
                            {% endfor %}
                        </div>

                        <button type="submit" class="btn btn-primary-hover-outline">Create Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/shop/contact.html
{% extends 'shop/base.html' %}
{% load form_tags %}
{% load static %}
{% block content %}
<div class="untree_co-section">
    <div class="container">
        <div class="block">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-8 pb-4">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label class="text-black" for="id_first_name">First name</label>
                                    {{ form.first_name|add_class:"form-control" }}
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label class="text-black" for="id_last_name">Last name</label>
                                    {{ form.last_name|add_class:"form-control" }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="text-black" for="id_email">Email address</label>
                            {{ form.email|add_class:"form-control" }}
                        </div>
                        <div class="form-group mb-5">
                            <label class="text-black" for="id_message">Message</label>
                            {{ form.message|add_class:"form-control" }}
                        </div>
                        <button type="submit" class="btn btn-primary-hover-outline">Send Message</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/shop/toggle_login.html
{% if user.is_authenticated %}
<div class="navbar-form navbar-right">
    <a class="dropdown-item" href="{% url 'shop:profile' %}">Your profile: {{ user.username }}</a>
    <a class="dropdown-item" href="{% url 'shop:logout' %}">Logout</a>
</div>
{% else %}
<form class="navbar-form navbar-right" method="POST" action="{% url 'shop:login' %}">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" placeholder="Username" name="username" class="form-control">
    </div>
    <div class="form-group">
        <input type="password" placeholder="Password" name="password" class="form-control">
    </div>
    <button type="submit" class="btn btn-success">Sign in</button>
</form>
{% endif %}