website/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('<int:order_id>/', views.order_detail, name='order_detail'),
]

website/shop/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from .views import MyLogoutView

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', views.blog, name='blog'),
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blog/create/', views.blog_create, name='blog_create'),
    path('services/', views.services, name='services'),
    path('terms/', views.terms, name='terms'),
    path('contact_success/', views.contact_success, name='contact_success'),
    path('support/', views.support, name='support'),
    path('register/', views.register, name='register'),
    path('checkout/', views.checkout, name='checkout'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('profile/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('shop/', views.product_list, name='product_list'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
]

website/shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'shopping_cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update/', views.cart_update, name='cart_update'),


]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('shopping_cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('create/', include(('orders.urls', 'create'), namespace='order_create')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/shopping_cart/models.py
from django.db import models

# Create your models here.

website/shopping_cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

website/shopping_cart/views.py
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('shopping_cart:cart_detail')  # Перенаправление на страницу корзины


def cart_detail(request):
    cart = Cart(request)
    cart_items = []
    for item in cart:
        # Проверяем, является ли item словарем или объектом
        product = item['product'] if isinstance(item, dict) else item.product
        quantity = item['quantity'] if isinstance(item, dict) else item.quantity
        total_price = product.price * quantity
        cart_items.append({
            'product': product,
            'quantity': quantity,
            'total_price': total_price,
        })
    return render(request, 'shopping_cart/detail.html', {'cart_items': cart_items, 'cart': cart})


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('shopping_cart:cart_detail')  # Перенаправление на страницу корзины

def cart_update(request):
    cart = Cart(request)
    if request.method == 'POST':
        for key, value in request.POST.items():
            if key.startswith('quantity_'):
                product_id = key.split('_')[1]
                try:
                    quantity = int(value)
                    if quantity > 0:
                        product = Product.objects.get(id=product_id)
                        cart.add(product, quantity=quantity, update_quantity=True)
                except Product.DoesNotExist:
                    continue

    return redirect('shopping_cart:cart_detail')  # Перенаправление на страницу корзины

website/templates/shopping_cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<div class="untree_co-section before-footer-section">
    <div class="container">
        <div class="row mb-5">
            <form class="col-md-12" method="post" action="{% url 'shopping_cart:cart_update' %}">
                {% csrf_token %}
                <div class="site-blocks-table">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-total">Total</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ item.product.image.url }}" alt="Image" class="img-fluid" width="100" height="100">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{ item.product.name }}</h2>
                                </td>
                                <td>${{ item.product.price }}</td>
                                <td>
                                    <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <button class="btn btn-outline-black decrease" type="submit" name="quantity_{{ item.product.id }}" value="{{ item.quantity|add:'-1' }}">&minus;</button>
                                        </div>
                                        <input type="text" class="form-control text-center quantity-amount" name="quantity_{{ item.product.id }}" value="{{ item.quantity }}" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-black increase" type="submit" name="quantity_{{ item.product.id }}" value="{{ item.quantity|add:'1' }}">&plus;</button>
                                        </div>
                                    </div>
                                </td>
                                <td>${{ item.total_price|floatformat:2 }}</td>
                                <td>
                                    <a href="{% url 'shopping_cart:cart_remove' item.product.id %}" class="btn btn-black btn-sm">X</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </form>
        </div>

        <div class="row">
            <div class="col-md-6">
                <!-- Остальной код -->
            </div>
            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>

                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">${{ cart.get_total_price }}</strong>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <a href="{% url 'orders:order_create' %}" class="btn btn-black btn-lg py-3 btn-block">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}